name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Memungkinkan Anda memicu build secara manual dari GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner (for Isar generated files)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Fix Isar Plugin Namespace (AGP 8+)
        run: |
          find ~/.pub-cache/hosted/pub.dev/isar_flutter_libs-*/android/build.gradle -type f -exec sed -i 's/group "dev.isar.isar_flutter_libs"/group "dev.isar.isar_flutter_libs"\n    namespace "dev.isar.isar_flutter_libs"/g' {} +

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: invoice-generator-apk
          path: build/app/outputs/flutter-apk/app-release.apk
